
spring:
  profiles:
    active:  dev
---
server:
  port: 8003
  
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.ouyi.springcloud.entity  # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   profiles: 8003-dev
   application:
    name: microservicecloud-config-dept-client-8003 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
 
   redis:
    database: 0       # Redis数据库索引（默认为0） 
    host: 192.168.1.230   # Redis服务器地址  
    port: 6379        # Redis服务器连接端口
    password:         # Redis服务器连接密码
    pool:
      max-active: 200   # 连接池最大连接数（使用负值表示没有限制）  
      max-wait: 1       # 连接池最大阻塞等待时间（使用负值表示没有限制）  
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 1       # 连接池中的最小空闲连接
    timeout: 1000       # 连接超时时间（毫秒）  
    
    
    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
     # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 集群
  instance: 
    instance-id: microservicecloud-config-dept-client-8003    #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
    
info:   # eureka中访问微服务的简单介绍
  app.name: ouyi-microservicecloud
  company.name: www.ouyi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

